parameters:
#    keyteq_demo_site.example.class: Keyteq\Bundle\DemoSiteBundle\Example

services:
#    keyteq_demo_site.example:
#        class: %keyteq_demo_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
